### ISSUE TITLE
divoom times gate

### ISSUE THREAD

**Issue by Famku** [4ch1m/pixoo-rest#14]
Hi,

is it possible to add divoom times gate?

**Comment by 4ch1m** [comment]
Hello,

The TimesGate device is not supported (yet).
However, there seem to be dedicated API commands for it: http://doc.divoom-gz.com/web/#/12?page_id=532

I don't own a Divoom Times Gate; so I can't implement/test features for it.

**Comment by Famku** [comment]
yes, all standard api commands working 

but I dont know how to assign a gif or text to the different screens

seems only this command is missing:

LcdArray | Array | [1,0,0,0,0] 1:display;0:pass

**Comment by 4ch1m** [comment]
Okay.
Since I don't own this device I unfortunately can't assist any further here.

To integrate it into this project (and possibly re-use all existing endpoints, etc.) a lot of refactoring/restructuring would have to be done.

I'm closing this issue for now.

However, mature/working pull-requests are always welcome.
