### ISSUE TITLE
Integration offizieller API

### ISSUE THREAD

**Issue by Azathoth88** [4ch1m/pixoo-rest#2]
Achim klingt deutsch, daher bin ich mal so frei: Ich bin jetzt durch Zufall auf deine Swagger-Integration gestoßen... Super Sache - danke dafür! Nun zum Thema:

Unter http://doc.divoom-gz.com/web/#/12?page_id=89 steht eine offizielle API-Beschreibung zur Verfügung. Vielleicht sind da noch unentdeckte Funktionen vorhanden.
Spannend dürfte hier insbesondere der **Find device** command sein. Vielleicht könnte man sich damit die Angabe des PIXOO_HOST sparen und automatisiert im Netzwerk nach dem Gerät suchen?

**Comment by 4ch1m** [comment]
> Achim klingt deutsch, daher bin ich mal so frei:

In the interest of the worldwide GitHub-community, english should be the preferred language here.

> Unter http://doc.divoom-gz.com/web/#/12?page_id=89 steht eine offizielle API-Beschreibung zur Verfügung. Vielleicht sind da noch unentdeckte Funktionen vorhanden. Spannend dürfte hier insbesondere der **Find device** command sein. Vielleicht könnte man sich damit die Angabe des PIXOO_HOST sparen und automatisiert im Netzwerk nach dem Gerät suchen?

I'm aware of this API-documentation and the "Find Device" command.
However, I'm not sure how that should be utilized in this context.
In order to talk to a device and/or send an API-request you'll need to have an (IP-)address or hostname.
I'm sure this command could be used to find _additional_ Pixoo-devices in the same network.
But i guess the initial request has to be made using a specific address.

But improvements are always welcome.
I'll gladly review your pull-request and merge it; if it works.

Closing, since this is not actually an issue.

**Comment by Azathoth88** [comment]
Hello Achim,
I am not a developer, but in a professional context I am a product owner. So I understand something about requirements management and roughly something about interfaces. However, I can't program that myself. I didn't know if you know the API, so this is just a friendly hint. If there are no adjustments, that's fine too. The API works.

**Comment by 4ch1m** [comment]
No offense. No worries. Just wanted to point out that this is a non-commercial and open-source hobby-project. Any contributions are very welcome. Based on your comment I personally just don't see any concrete possibilities for useful/additional implementations here.
